### ISSUE TITLE
what format, i know its labled text but how to read?

### ISSUE THREAD

**Issue by gaming09** [hkphh/rockyou2024.txt#1]
how to read ? is it plaintext inside the text file?

**Comment by hkphh** [comment]
You'll download .zip archive
Inside archive plain text .txt file 
The simplest usage - grep -e "pattern" rockyou2024.txt -> will return ur pattern string
Otherwise you can use it as pass wordlist in tools like hashcat

**Comment by hkphh** [comment]
I found some tools written on C, witch can help you to fast read this file
https://github.com/mikemadden42/rockyou2024
