### ISSUE TITLE
Unique passwords?

### ISSUE THREAD

**Issue by juliocruces** [hkphh/rockyou2024.txt#4]
Hello, does it contain unique passwords without duplicates?
Does the other one contain passwords from the previous rockyou?. 

Thanks

**Comment by hkphh** [comment]
It doesnt contain duplicates (based on my experience)
2024 version contain the older one rockyou2021
you can read a small rockyou2024 analysis
https://specopssoft.com/blog/rockyou2024-analysis-password-leak/
